namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/prober@sha256:1d12dfb24baa55339fa6ca6f40836c39aba6ffc407ebd0b611670c6f00738cc4  # v0.4.9
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  args:
    fulcioHost: https://fulcio.sigstore.dev
    rekorHost: https://rekor.sigstore.dev
    frequency: 10
    writeProber: false
prometheus:
  port: 8080
